### ISSUE TITLE
Enhanced support for doppelganger domains

### ISSUE THREAD

**Issue by mateuszz0000** [atenreiro/opensquat#20]
Is anyone working on this issue right now? If not can I take it? 

Do you have any useful resources about cyber squatting?

**Comment by atenreiro** [comment]
I had this in my list but I think the openSquat is somehow effective against doppelganger. This attack is usually used for phishing, for example:

user@acme.company.com (legit) --> user@acme-company.com (doppelganger)

It will detect the "company" string inside the "acme-company" and it might also detect using Leven/Jiro is the threshold is medium/low. 

What are your thoughts about the current effectiveness against doppelganger?

**Comment by mateuszz0000** [comment]
Yes, Leven / Jiro will detect doppelganger with a calculation of chain similarity. How about the functionality of checking only doppelganger in given domains as an option?

**Comment by atenreiro** [comment]
Yes, that can work.

So basically, the doppelganger check method will only verify if the keyword string is contained inside the domain and will not check against Leven/Jiro. This should be really fast to compute the whole list.

Want to work on what?

**Comment by mateuszz0000** [comment]
Yes, it will be an easy task.
