### ISSUE TITLE
Support CRT.SH (certificate transparency)

### ISSUE THREAD

**Issue by mateuszz0000** [atenreiro/opensquat#22]
Hello,

I found this issue in https://github.com/atenreiro/opensquat/projects/1. I could work on this :)

**Comment by atenreiro** [comment]
Hi Mateusz,

That would be great!

The idea behind CRT.SH is to make use of certificate transparency (CT) to search for sub-domains, for example: paypal.com.random-domain.com

Fraudsters create subdomains that look like the legit domain to trick users to believe this domain is legit and has got the "HTTPS green lock".

We can conduct a doppelganger search method for CRT.SH

Any other thoughts?

**Comment by mateuszz0000** [comment]
Understand. I found more engines that collect CT logs exept crt.sh such as:
* https://censys.io/
* https://developers.facebook.com/tools/ct/
* https://google.com/transparencyreport/https/ct/
We could have much more domain collection.

So basically we want to scan found doppelganger domains for CT ?

**Comment by atenreiro** [comment]
I'm familiar with Censys but not the other two, so I will have to investigate.

I have tested Censys before with openSquat, the challenge is that you need an API-key to query the data which is free but usually rate-limited (e.g: 1000 queries per day).

**Comment by atenreiro** [comment]
Just a tip:

Usually fraudsters use "Let's Encrypt Authority X3" has the issuer authority because it's free.

**Comment by atenreiro** [comment]
FB needs an account (key) but Google does not. However, I'm not sure if we can simply scrap the information from Google CT website? Probably need to read the T&C

**Comment by mateuszz0000** [comment]
So I think the best option for now is implementation only for crt.sh but designed in that way when we could extend this mechanism for various engines.

**Comment by atenreiro** [comment]
Fully agreed.

**Comment by atenreiro** [comment]
Hey Mateusz! 
I found a small bug :-)

![image](https://user-images.githubusercontent.com/10222828/82934293-8d699980-9f8b-11ea-8e2c-5dea552b9ee0.png)

**Comment by mateuszz0000** [comment]
I will check it! :rocket: Here is a weird domain i guess. Interesting...
