### ISSUE TITLE
Social Media - Instagram

### ISSUE THREAD

**Issue by atenreiro** [atenreiro/opensquat#29]

**Comment by atenreiro** [comment]
Simple validation:

![image](https://user-images.githubusercontent.com/10222828/83953399-6e4af180-a840-11ea-8b03-e40b7da8e2c6.png)

**Comment by mateuszz0000** [comment]
Is this version on branch `instagram` ready to merge? Looks good :smiley:

**Comment by atenreiro** [comment]
No, I think I still need some more work, but I will soon release. 

I rather have short development cycles with small improvements than longer cycles with major enhancements.

**Comment by atenreiro** [comment]
This issue will be moved to a lower priority.
