### ISSUE TITLE
Domain data download fails for day and month data

### ISSUE THREAD

**Issue by sw-mschaefer** [atenreiro/opensquat#30]
Running the tool with day or month range is no longer possible since "domain-names.txt" and "domain-names-month.txt" are no longer existing in the https://github.com/CERT-MZ/projects/tree/master/Domain-squatting repository.

**Comment by atenreiro** [comment]
Fixed.

Thanks for reporting.

**Comment by sw-mschaefer** [comment]
Thanks. Would be a nice enhancement if the script fails in case the download location is 404.

**Comment by atenreiro** [comment]
Thanks, will take this into consideration in the next release. Feel free to add more suggestions.

**Comment by atenreiro** [comment]
Enhancement added to in case the file can't be download or not found.
