### ISSUE TITLE
Question:where does the "fresh domain list" come from?

### ISSUE THREAD

**Issue by kak-to-tak** [atenreiro/opensquat#40]
First of all, thank you for the tool!

Could you please specify where does the "fresh domain list" come from? How "fresh" is it? Where does "fresh Phishing DB" come from? How often is it updated?

**Comment by atenreiro** [comment]
Hello @kak-to-tak 

The domain list comes from a private feed and it's updated once a day. There's usually a 24-48h lag between the registration to be available to openSquat.

For the Phishing domains, I get from this project:
[https://github.com/mitchellkrogza/Phishing.Database](https://github.com/mitchellkrogza/Phishing.Database)

I hope this answers both questions.

**Comment by kak-to-tak** [comment]
Thank you!
I have another question: suppose I don't have keywords, but have urls which I need to check on fishing? How would I do that?

**Comment by atenreiro** [comment]
> Thank you!
> I have another question: suppose I don't have keywords, but have urls which I need to check on fishing? How would I do that?

Hi best way is to extract part of the word from the URL. 

Example: acme-company.com 

You can include in the **keywords.txt** file either the word: acme, company or acme-company.

**Comment by atenreiro** [comment]
@kak-to-tak 

If you find somehow openSquat helpful, do you mind if you can help the project by posting on social networks about this tool? Hopefully, more people will join the community and contribute to enhancing the tool either with code or fresh new ideas.

Thanks in advance!

**Comment by kak-to-tak** [comment]
Thank you!
