### ISSUE TITLE
Daily feed is down

### ISSUE THREAD

**Issue by wargasmtg** [atenreiro/opensquat#41]
Seems Opensquat is no longer able to pull the daily feed

+---------- Checking Domain Squatting ----------+
[*] Downloading fresh domain list from https://raw.githubusercontent.com/CERT-MZ/projects/master/Domain-squatting/domain-names.txt
[ERROR] domain-names.txt not found,trying the weekly file.
[*] Downloading fresh domain list from https://raw.githubusercontent.com/CERT-MZ/projects/master/Domain-squatting/domain-names-week.txt
[ERROR] File not found! Contact the authors or try again later. Exiting...

**Comment by atenreiro** [comment]
Hello @wargasmtg 

You are running an outdated version, that feed URL was decommissioned in the 30th September. 

To keep using openSquat just update it by running:

`$ git pull`

And everything should come back online with a new feed URL.

**Comment by wargasmtg** [comment]
Works! And thanks again!

**Comment by atenreiro** [comment]
Awesome!

Good hunting ✌🏻
