### ISSUE TITLE
Question: How many new domains appear in the feed daily?

### ISSUE THREAD

**Issue by kak-to-tak** [atenreiro/opensquat#42]
Is it possible to find out when a particular domain was added?
How many appear daily?
To check how many of them are already dead or for sale?

**Comment by atenreiro** [comment]
Hello @kak-to-tak 

If you want to search is a specific domain was added (e.g: acme-website.com) you can just insert the "acme-website" word inside the keywords.txt

the daily average over the last 30 days was 115,680 daily domains. 

What you mean by dead or on sale? If you want to check if the domain is ACTIVE, you can add the --portcheck flag, this will verify if the webservers port 80/443 is open or not.

**Comment by atenreiro** [comment]
Closing due inactivity
