### ISSUE TITLE
How to use Virustotal?

### ISSUE THREAD

**Issue by wargasmtg** [atenreiro/opensquat#44]
Hello, 

After I run opensquat how do I check the results.txt against virustotal within opensquat?

Thank you

**Comment by atenreiro** [comment]
Hello @wargasmtg 

At this present moment, VT integration is not available. I can try to fast-track this for you if this is a feature request.

There is a feature that might help you right now. The openSquat is integrated with [Quad9](https://quad9.net/) so you can validate if the domain is flagged as malicious or not. You can run this with the following syntax:

Quad9 validation:
`$ python3 opensquat.py --dns`

Let me know if this helps or not?

**Comment by atenreiro** [comment]
Hello @wargasmtg

At this present moment, VT integration is not fully available however, there's a couple of options that might help you.

**Quad9 validation:**
```
# This will validate if the domain is flagged against [Quad9 service](https://quad9.net/).
$ python3 opensquat.py --dns
```

**Subdomain check:**
```
# This will list other subdomains acme.domain.com from VirusTotal.
$ python3 opensquat.py --subdomains
```

I can look at this as a feature request, just do the following:

**README.md**
`To request for a new feature, create a "new issue" and describe the feature and potential use cases. If something similar already exists, you can upvote the "issue" and contribute to the discussions.`

**Comment by wargasmtg** [comment]
aha okay, when I read Integration with VirusTotal I assumed a different integration :)  Thanks. Quad9 works great thanks, would be cool if that showed up in the results.txt though

**Comment by atenreiro** [comment]
I think the description can be indeed misleading, I will fix that. Thanks
