### ISSUE TITLE
Issue with the daily feed

### ISSUE THREAD

**Issue by wargasmtg** [atenreiro/opensquat#45]
Hello, 

It looks like the daily domain names list is stuck in a loop. I keep getting the same domain name results for the last 2 days. 

When I look at https://phishydomains.com/  the number of domain names yesterday was 126735 
But when I pull the domain names list it is  92460

[*] Checking for the latest feeds...
[*] You have the latest feeds

[*] keywords: keywords.txt
[*] keywords total: 95
[*] Total domains: 92460
[*] Threshold: high confidence

[*] Verifying keyword: financien [ 1 / 95 ]
[+] Found afhandelingen-financien.site 
[+] Found belgiumfinancien.site 
[+] Found financien-betaling.online 
[+] Found financieninbeeld.com 
[+] Found inbeslagname-financien.site 

Thanks.

**Comment by atenreiro** [comment]
Hello @wargasmtg 

Thanks for letting me know! I moved the backend to another server and there was a configuration parameter that I missed.

Apologies for that, it's fixed now.
