### ISSUE TITLE
Release Notes 1.97

### ISSUE THREAD

**Issue by atenreiro** [atenreiro/opensquat#46]
**v1.97 (2020-10-18)**
- Domains can be verified is they are blacklisted to any VirusTotal engine
- You can now filter results using different args
- minor change, the number of domains showing with the thousand comma 

When using [VirusTotal](https://www.virustotal.com), the website throttles the queries if a large number of queries in a short time is detected.

**Comment by wargasmtg** [comment]
Perhaps it is better load the results into opensquat again with the use of the VT API key and que the results 4 each minute?

**Comment by wargasmtg** [comment]
Perhaps this project has some good ideas to implement into opensquad; https://github.com/clairmont32/VirusTotal-Tools

**Comment by atenreiro** [comment]
Hello @wargasmtg 

An integration with VT API key if planned, however, I decided to start with non-API integration. You'll be able to introduce your VT API key in a configuration file and the openSquat will load this key, whether is a free or premium subscription.

**Comment by wargasmtg** [comment]
Cool!
