### ISSUE TITLE
No attribute port checl?

### ISSUE THREAD

**Issue by wargasmtg** [atenreiro/opensquat#47]
I am running the latest version, but I am getting this error; 

[*] Verifying keyword: nescafe [ 101 / 102 ]
>> Progress: 98.5 %

[*] Verifying keyword: mastercard [ 102 / 102 ]
>> Progress: 99.0 %
>> Progress: 99.6 %
Traceback (most recent call last):
  File "opensquat.py", line 78, in <module>
    or args.portscheck:
AttributeError: 'Namespace' object has no attribute 'portscheck'

**Comment by atenreiro** [comment]
**oh snap!** 

Bug fixed. It was a typo:  "portcheck" and not "portscheck".

Please pull the latest version.

Thanks!

**Comment by wargasmtg** [comment]
Works once more!
