### ISSUE TITLE
Add whoisrd datasource

### ISSUE THREAD

**Issue by uBadRequest** [atenreiro/opensquat#48]
**Is your feature request related to a problem? Please describe.**
We need to pull in more domains. Lets use whoisds.com

**Describe the solution you'd like**
```
def getNewlyRegisteredDomains(self, date, output_path):
        base64_date = base64.b64encode((date + '.zip').encode()).decode()
        url = 'https://www.whoisds.com/whois-database/newly-registered-domains/' + base64_date + '/nrd'
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.2; Trident/7.0; rv:11.0) like Gecko'}
        result = requests.get(url, headers=headers)
        statuscode = result.status_code
        if statuscode == 200:
            with open(output_path, 'wb') as f:
                f.write(result.content)
            return True
        else:
            return False
```

**Comment by atenreiro** [comment]
Hello @uBadRequest 

Sorry I missed the issue notification. 

From what I could see, the domains from whoisds are already included in the daily openSquat feeds (domain-names.txt)

Is there any domain/ccTLD that is available at whoisds but not in the openSquat feeds?
