### ISSUE TITLE
Daily domains not updated

### ISSUE THREAD

**Issue by wargasmtg** [atenreiro/opensquat#49]
Hello, 

Daily domains list not updated for the last two days.  I did a pull but that did not fix the issue. 

Thank you

**Comment by atenreiro** [comment]
Hello @wargasmtg 

Not sure if the issue was fixed by itself but I'm able now to download the domain lists. It's possible that I had a backend issue to fetch the lists.

Thanks, and please keep reporting problems like this 👍 :)

Regards,
