### ISSUE TITLE
Daily domain feed not updating

### ISSUE THREAD

**Issue by wargasmtg** [atenreiro/opensquat#52]
Happy new year!

The daily domain feed is not updating since 48 hours.

**Comment by atenreiro** [comment]
Happy new year @wargasmtg 

Once again, thanks for reporting issues, truly appreciated! 

I have tested now and seems fully working. Probably, when you reported we had an issue with the feeds that were self-corrected. The database is updated daily between 8h/8h30 am (UTC).

I could see something out of the ordinary:
1) The days 2020-12-30 and 2020-12-31 the database had no update. 
2) There was an update missing for the 2021-01-01, I will revise my backend script to check if the error in the backend or from the private feeds that I receive.

Thanks,

**Comment by wargasmtg** [comment]
Yes I noticed it is working again. 

Todays list was rather small. Either TLDs are missing, or it was just super slow registration wise. We will find out more tomorrow :)

**Comment by wargasmtg** [comment]
Today's list is around 240k, seems things are back to normal.

**Comment by atenreiro** [comment]
Yeas, probably accumulated missing updates from previous days.
