### ISSUE TITLE
Quad 9 results

### ISSUE THREAD

**Issue by wargasmtg** [atenreiro/opensquat#54]
Hello, 

When I run the daily scan I have around 1500+ suspicious domain names. 
After I check with quad 9 I got around 700 malicious domain names. 

How can I get an overview/export of those malicious domain names so I can paste and copy them?
![Screenshot from 2021-02-28 10-55-06](https://user-images.githubusercontent.com/53938619/109414496-7856e680-79b3-11eb-9bef-38a9719330ed.png)

As you can see this is pretty hard to put in a spreadsheet and filter out the malicious stuff

**Comment by atenreiro** [comment]
Hello  @wargasmtg 

Do you want to export only the domains identified as "Malicious"?

**Comment by wargasmtg** [comment]
yes, an export of all the malicious marked domain names would be great. Could be something through the CLI which parses the results.txt and exports all the malicious stuff found in the results.txt. 

Thanks!

**Comment by atenreiro** [comment]
Ok, let me add this feature to the next release.

**Comment by wargasmtg** [comment]
Awesome, that will be great!
