### ISSUE TITLE
Latest feeds

### ISSUE THREAD

**Issue by wargasmtg** [atenreiro/opensquat#55]
Hello, 

For the last two days, OS is not pulling the latest feeds.

**Comment by atenreiro** [comment]
Hello,

After investigating this in the backend, I think the problem is with our private feed provider. I have reported to them.

Thanks for reporting!

**Comment by wargasmtg** [comment]
Can you perhaps ask them why .shop and .org is not included in the feed? These two TLDs are pretty large

**Comment by atenreiro** [comment]
> Can you perhaps ask them why .shop and .org is not included in the feed? These two TLDs are pretty large

I will do my best. Do you have any other source that I can pull more domains from?

**Comment by wargasmtg** [comment]
Not really 

I did use https://www.whoisextractor.in in the past, but I thought it was somewhat limited, not sure how things are nowadays.
