### ISSUE TITLE
Not pulling the daily feed for some days now

### ISSUE THREAD

**Issue by wargasmtg** [atenreiro/opensquat#58]
Hello, 

It seems the daily feed is stuck somewhere, it keeps returning that I have the latest feeds.

**Comment by atenreiro** [comment]
Hello  @wargasmtg 

Thanks for reporting - all seems ok now! There must be a delay in the database, sometimes it happens.

Regards,

**Comment by wargasmtg** [comment]
Maybe on your side :)  but it has not been pulling a new feed since Thursday.  Keeps pulling a feed with 88062 domains.

**Comment by wargasmtg** [comment]
I am using the following command  python3 opensquat.py -p day   I assume that command is still valid?

**Comment by atenreiro** [comment]
oops... oh no :-(

Let me check that

**Comment by atenreiro** [comment]
Can you check if this is fixed now?

**Comment by wargasmtg** [comment]
it is fixed, thanks!

**Comment by atenreiro** [comment]
No, thank YOU! 

You're the openSquat community HERO :-)
