### ISSUE TITLE
[Windows] No Colours

### ISSUE THREAD

**Issue by atenreiro** [atenreiro/opensquat#6]
Colorama colour scheme is not showing on Windows terminal.

**Comment by mateuszz0000** [comment]
The problem is caused by the lack of ANSI by Windows. Here is a discussion on this topic. I've tried solution with
 ```
from colorama import init
init()
``` and it almost works but colors are different (green instead blue). 

Perhaps adding `help wanted` and `good first issue` labels will bring someone experienced here with this topic :)

**Comment by atenreiro** [comment]
Yes, this is actually easy to fix just not working on this as a priority. I list here to keep in the list :-) 

changed to "good first issue"
