### ISSUE TITLE
Daily database not updating

### ISSUE THREAD

**Issue by wargasmtg** [atenreiro/opensquat#61]
Hi, 

The daily database is no longer updating since yesterday.

**Comment by atenreiro** [comment]
Hello @wargasmtg 

Sorry for the delays, I was out for a couple. It seems like the "old problem" from the private feeds - it does happen from time to time and usually recovers again. Thanks for reporting.

**Comment by wargasmtg** [comment]
hello

Let's hope it picks up at some time, thanks for checking on your end.

**Comment by atenreiro** [comment]
Resolved
