### ISSUE TITLE
(Possible bug) Double DNS reputation check

### ISSUE THREAD

**Issue by xnomas** [atenreiro/opensquat#63]
Hi! 

I was reading through your source code, and noticed that in the `app.py` file, there is a duplicate DNS reputation check in the `_process_levenshtein` function.

A DNS check happens, even if the flag is not set, as can be seen [here](https://github.com/atenreiro/opensquat/blob/master/opensquat/app.py#L430):
```py
        elif (leven_dist <= self.confidence_level) and homograph_domain:
            self.on_homograph_detected(
                keyword,
                domains,
                self.confidence[leven_dist]
                )
            self.dns_reputation(domains)

            #  DNS Validation
            if(self.dns_validation):
                self.dns_reputation(domains)
```
ie. if `self.dns_validation` is True, then `dns_reputation` gets called twice:] 

Cheers.

**Comment by atenreiro** [comment]
Oh! Yes, that must be a bug 🐞😩

Thanks for reporting this, will take a look at it.

**Comment by xnomas** [comment]
Just deleting that one extra `self.dns_reputation` line should be enough :] Feels unnecessary to open a PR for that, so I'll leave it up to you! :]
