### ISSUE TITLE
Daily new domains

### ISSUE THREAD

**Issue by wargasmtg** [atenreiro/opensquat#65]
Hello, 

It seems after the new update the number of daily domain names dropped below 3000
![daily](https://user-images.githubusercontent.com/53938619/164171583-e7f64b02-92fc-4088-9ad4-a3ce3f2ee427.PNG)
 domains?

**Comment by atenreiro** [comment]
Hey @wargasmtg 

I noticed as well, but that's what has been received from the feed provider.

Maybe today & tomorrow they'll provide an accumulated missing feed from the previous days.

**Comment by wargasmtg** [comment]
They are back! :)
