### ISSUE TITLE
Error While Installing Requirements

### ISSUE THREAD

**Issue by RiteshSec** [atenreiro/opensquat#69]
ERROR: Could not find a version that satisfies the requirement black (from -r requirements.txt (line 11)) (from versions: none)
ERROR: No matching distribution found for black (from -r requirements.txt (line 11))

![image](https://user-images.githubusercontent.com/110530131/184287445-b0b8da80-7e87-4c15-b021-a6eaea4e8bd5.png)

**Comment by RiteshSec** [comment]
> ERROR: Could not find a version that satisfies the requirement black (from -r requirements.txt (line 11)) (from versions: none) ERROR: No matching distribution found for black (from -r requirements.txt (line 11))
> 
> ![image](https://user-images.githubusercontent.com/110530131/184287445-b0b8da80-7e87-4c15-b021-a6eaea4e8bd5.png)

Issue Resolved when used pip3 to install requirements and and python3 to run the code

**Comment by atenreiro** [comment]
Ok, perfect! 👌
