### ISSUE TITLE
PEP8/CI/CD 

### ISSUE THREAD

**Issue by mateuszz0000** [atenreiro/opensquat#7]
Hello,
Do you have any idea about pep8 compiliance with some CI/CD (regarding tasks in project roadmap)?

My proposal is standard stack: black, flake8, pytest running on TravisCI.

**Comment by atenreiro** [comment]
Hello mateuszz0000,

I will work on PEP8 for this week. No plans yet for the CI/CD as I'm still working in the backlog. Do you want to look at that?

**Comment by mateuszz0000** [comment]
Sure!

**Comment by atenreiro** [comment]
Nice job! :-)

I've added the build status icon to the README.md

https://travis-ci.com/atenreiro/opensquat
