### ISSUE TITLE
Target response informations

### ISSUE THREAD

**Issue by t0sc4n** [atenreiro/opensquat#70]
Feature request: Site response informations

It would be useful to have informations about the potential squatted site information, such as:

- Response code
- If keyword is response html
- If some phishing-related keywords are present in the response html
- Notice SSL connection errors

I've developed a very simple solution locally and I think it would be a useful addition to the project. 
If the feature request is accepted, I can make a pull request

**Comment by atenreiro** [comment]
Hey @t0sc4n 

Would you be able to share the fork for me to test so I can better understand the feature?

Thanks,

**Comment by t0sc4n** [comment]
Hi @atenreiro, sure!

Here you go https://github.com/atenreiro/opensquat/pull/71.

Thanks
