### ISSUE TITLE
Domain download sending the same file every day

### ISSUE THREAD

**Issue by dindjarinmando** [atenreiro/opensquat#72]
Mate, appears that the domain feed is downloading the same list every day.

**Comment by atenreiro** [comment]
> Mate, appears that the domain feed is downloading the same list every day. 

Hey @dindjarinmando 

Thanks for reporting back, unfortunately we are having a few issues with our feeds. I hope this should be cleared out by tomorrow or Thursday.

In another note, I am looking to improve our feed reliability.

**Comment by dindjarinmando** [comment]
Cheers!
