### ISSUE TITLE
RapidAPI question

### ISSUE THREAD

**Issue by dindjarinmando** [atenreiro/opensquat#73]
Mate, do you have plans to set up other endpoints with RapidAPI? Maybe the domain list feed?

**Comment by atenreiro** [comment]
Hey @dindjarinmando buddy

The domain issue seems fixed for now.

I'm not sure if I understood your question about the RapidAPI, what's your use case?

Thanks

**Comment by dindjarinmando** [comment]
Cheers! No use case, just curious.
