### ISSUE TITLE
Error Starting OpenSquat

### ISSUE THREAD

**Issue by phoenixml** [atenreiro/opensquat#77]
Hi All thank you for this project, I was looking to a domains monitoring and came across this project: 
1- I downloaded the repo and installed the requirements.
2- Started the lazy script to test it 
3-  I am facing the below issue:
![image](https://user-images.githubusercontent.com/14360476/211532713-be52f4ed-b106-47bd-b58a-b7b7190b592b.png)

If I ran the script without elevation It is running but complaining about not be able to save the domain-names.txt
If I ran the script as sudo then i am having python errors. 
Any ideas your help is appreciated.

Cheers,

**Comment by atenreiro** [comment]
Hello @phoenixml 

The script does not require sudo privileges. 

Could you let me know if you installed the library requirements? If not, you can do this with following command:

`ubuntu@localhost:~/opensquat$ pip install -r requirements.txt`

**Comment by phoenixml** [comment]
Hi @atenreiro  appreciated your reply. yeah, I did that but I can remember that I saw some errors with some libraries. I will reinstall might be these missing dependencies and update you.

Cheers.

**Comment by atenreiro** [comment]
Can you show the output of the following commands:

**Python version:**
`ubuntu@localhost:~/opensquat$  python --version`

**Library requirements:**
`ubuntu@localhost:~/opensquat$ pip install -r requirements.txt`

Note: You may replace "pip" with the "pip3" command

**Comment by phoenixml** [comment]
Hi @atenreiro I have python 3.10.6
![image](https://user-images.githubusercontent.com/14360476/212315234-21e6603d-a2e2-438b-aff9-c38c4618e065.png)

Thank you appreciated your follow up

**Comment by phoenixml** [comment]
ok I imported the missing modules and fixed the folder permission for non root and now it is working thank you @atenreiro  I will close this one appreciated your help.
