### ISSUE TITLE
Jaro-Winkler implementation as an alternative to Levenshtein.

### ISSUE THREAD

**Issue by mateuszz0000** [atenreiro/opensquat#9]
Can I work on this problem? If so, do you have a special idea?
I was thinking of a CLI command like `--method levenshtein / jarowinkler`. As a result, confidence checks will vary depending on the results of different methods.

**Comment by atenreiro** [comment]
Hi Mateus,

You can definitely work on it, the function is already is implemented.

It's a slightly different method and I would consider the following confidence scores:

Very high: 0.950 and above
High: 0.900 to 0.949
Medium: 0.800 to 0.890
Low: below 0.800

These values can be easily adjusted.

The good thing about Jaro, it's approximately 3x faster than Levenshtein.
