### ISSUE TITLE
domain-names.txt comes with question marks "?" 

### ISSUE THREAD

**Issue by SMP2023** [atenreiro/opensquat#99]
Hi,
In recent days the file that contains the list of new domains (NRD) comes with question marks "?" in the domain names.
I would appreciate it if you could look into the matter.
Thank you very much!
Sam

**Comment by atenreiro** [comment]
Hello Sam,

Thanks for bringing this. This seems like a unicode issue with some Chinese characters - I am attempting to fix this.

**Comment by SMP2023** [comment]
Thank you!
